name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      
    - name: Setup Python
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
      with:
        python-version: '3.11'
        
    - name: Setup Miniconda
      run: |
        # Download and install Miniconda
        # Pin Miniconda version and verify checksum
        MINICONDA_VERSION=py311_24.1.2-0
        MINICONDA_URL="https://repo.anaconda.com/miniconda/Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh"
        MINICONDA_SHA256="3f2e5498e550a6437f15d9cc8020d52742d0ba70976ee8fce4f0daefa3992d2e"
        wget "$MINICONDA_URL" -O miniconda.sh
        echo "$MINICONDA_SHA256  miniconda.sh" | sha256sum -c -
        bash miniconda.sh -b -p $HOME/miniconda
        export PATH="$HOME/miniconda/bin:$PATH"
        echo "$HOME/miniconda/bin" >> $GITHUB_PATH
        # Initialize conda for this shell session
        eval "$($HOME/miniconda/bin/conda shell.bash hook)"
        # Configure conda
        conda config --set channel_priority strict
        conda config --add channels conda-forge
        conda config --set auto_activate_base false
        
    - name: Install NEST Simulator
      run: |
        source $HOME/miniconda/bin/activate
        conda create -n nest-env python=3.11 -y
        conda activate nest-env
        conda install -c conda-forge nest-simulator -y
        echo "CONDA_DEFAULT_ENV=nest-env" >> $GITHUB_ENV
        echo "$HOME/miniconda/envs/nest-env/bin" >> $GITHUB_PATH
        
    - name: Install build dependencies
      run: |
        source $HOME/miniconda/bin/activate nest-env
        python -m pip install --upgrade pip
        pip install build twine
        
    - name: Build package
      run: |
        source $HOME/miniconda/bin/activate nest-env
        python -m build
      working-directory: ./PyNEST
      
    - name: Check package
      run: |
        source $HOME/miniconda/bin/activate nest-env
        python -m twine check PyNEST/dist/*
      
    - name: Test package before publishing
      run: |
        source $HOME/miniconda/bin/activate nest-env
        # Install the built package
        pip install PyNEST/dist/*.whl
        # Test NEST availability
        python -c "import nest; print(f'NEST version: {nest.__version__}')"
        # Test import
        python -c "import microcircuit; print(f'Successfully imported microcircuit version {microcircuit.__version__}')"
      
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        source $HOME/miniconda/bin/activate nest-env
        python -m twine upload PyNEST/dist/* --verbose
