name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@835234971496cad1653abb28a638a281cf32541f
      with:
        auto-update-conda: true
        python-version: '3.11'
        channels: conda-forge
        channel-priority: strict
        conda-remove-defaults: true
        activate-environment: build-env
        
    - name: Install NEST Simulator
      shell: bash -l {0}
      run: |
        conda install -c conda-forge nest-simulator -y
        
    - name: Install build dependencies
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        
    - name: Build package
      shell: bash -l {0}
      run: python -m build
      working-directory: ./PyNEST
      
    - name: Check package
      shell: bash -l {0}
      run: python -m twine check PyNEST/dist/*
      
    - name: Test package before publishing
      shell: bash -l {0}
      run: |
        # Install the built package
        pip install PyNEST/dist/*.whl
        # Test NEST availability
        python -c "import nest; print(f'NEST version: {nest.__version__}')"
        # Test import
        python -c "import microcircuit; print(f'Successfully imported microcircuit version {microcircuit.__version__}')"
      
    - name: Publish to PyPI
      shell: bash -l {0}
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m twine upload PyNEST/dist/* --verbose
